app_movies/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name="home"),
    path('', include('users.urls', namespace="users")),
    path('movies/', include('movies.urls', namespace="movies")),
    path('admin/', admin.site.urls),
]

app_movies/movies/urls.py
from django.urls import path, include

from rest_framework import renderers, routers
from movies import views


app_name = "movies"

router = routers.DefaultRouter()
router.register(r'category', views.CategoryViewSet)
router.register(r'keyword', views.KeywordViewSet)
router.register(r'movie', views.MovieViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('page-movies', views.HomePage.as_view(), name='home_movies'),
    path('api-movies', views.ApiPage.as_view(), name='api_movies'),
]



app_movies/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
]

app_movies/movies/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Name category')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Keyword(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='key Word')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    year = models.IntegerField(default=1900, verbose_name='Year')
    summary = models.CharField(max_length=500, verbose_name='Plot Summary')
    categories = models.ManyToManyField(Category, verbose_name='Categories')
    keywords = models.ManyToManyField(Keyword, verbose_name='Keywords')
    poster = models.CharField(max_length=500, null=True, blank=True, verbose_name='url_poster')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app_movies/users/models.py
from django.db import models

# Create your models here.

app_movies/movies/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.response import Response
from rest_framework import viewsets

from movies.serializers import CategorySerializer, KeywordSerializer, MovieSerializer
from movies.models import Category, Keyword, Movie


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'movies/movies_page.html'


class ApiPage(LoginRequiredMixin, TemplateView):
    template_name = 'movies/api_movies.html'    

    
class CategoryViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Category.objects.all().order_by('name')
    serializer_class = CategorySerializer


class KeywordViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Keyword.objects.all().order_by('name')
    serializer_class = KeywordSerializer


class MovieViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Movie.objects.all().order_by('title')
    serializer_class = MovieSerializer

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
        except Http404:
            pass
        return Response(status=status.HTTP_204_NO_CONTENT)


app_movies/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })

app_movies/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}Catalog Movies{% endblock %}</title>
  <style type="text/css">
    .asteriskField {
      display: none;
    }

    form .alert ul li {
      list-style: none;
    }

    form .alert ul {
      padding: 0;
      margin: 0;
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Catalog Movies</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:home_movies' %}">Movies</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:api_movies' %}">Documentation API</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'users:password_change' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline my-2 my-lg-0">
            <a href="{% url 'users:login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'users:signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  {% block scripts %}
  {% endblock %}
</body>
</html>

app_movies/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sample API MOVIES</h2>
  <p>Welcome to My Site, {% if user.is_authenticated %}{{ user.username }}{% else %}visitor{% endif %}!</p>

{% endblock %}

app_movies/templates/movies/api_movies.html
{% extends 'base.html' %}

{% block content %}
  <h2>Example use api</h2>
  <p>List objects</p>
  <a class="nav-link" href="{% url 'movies:movie-list' %}">Movies List</a>
  <a class="nav-link" href="{% url 'movies:category-list' %}">Categories List</a>
  <a class="nav-link" href="{% url 'movies:keyword-list' %}">KeyWords List</a>
  <br>
  <p>Detail objects</p>
  <a class="nav-link" href="{% url 'movies:movie-detail' 1 %}">Movies detail: 1</a>
  <a class="nav-link" href="{% url 'movies:category-detail' 1  %}">Categories detail: 1</a>
  <a class="nav-link" href="{% url 'movies:keyword-detail' 1 %}">KeyWords detail: 1</a>


{% endblock %}

app_movies/templates/movies/movies_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <p>List Movies</p>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div id="movies-list"></div>
    </div>
    <div class="col-sm">
      <div id="detail-list"></div>
    </div>
  </div>
</div>

 <!-- Modal -->
  <div class="modal fade" id="modalUpdate" role="dialog">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Update Movie</h4>
          </div>
          <div class="modal-body" id="formUpdate">
                        
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>


  
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}